n = input ('digite algo aqui : ')

print ('o tipo é', type(n))
print ('so tem espaços? ',n.isspace())
print ('é um numero',n.isnumeric())
print ('é alfabetico? ',n.isalpha())
print ('é alfanumerico? ',n.isalnum())
print ('esta em maiusculo? ',n.isupper())
print ('esta em minusculo? ',n.islower())
print ('esta capitalizada? ',n.istitle())
